spring:
  profiles:
    include: oauth
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 4
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  redis:
#    host: ${REDIS_HOST}
#    port: ${REDIS_PORT}